#ifndef LED_H_
#define LED_H_

#include <stdio.h>
#include <stdint.h>
#include "PinDefines.h"
#include "system_stm32f10x.h"
#include "stm32f10x_gpio.h"
#include "main.h"

//on board leds
#define LED1_OFF GPIO_SetBits(LED1_GPIO, LED1_PIN)
#define LED2_OFF GPIO_SetBits(LED2_GPIO, LED2_PIN)
#define LED3_OFF GPIO_SetBits(LED3_GPIO, LED3_PIN)
#define LED4_OFF GPIO_SetBits(LED4_GPIO, LED4_PIN)

#define LED1_ON GPIO_ResetBits(LED1_GPIO, LED1_PIN)
#define LED2_ON GPIO_ResetBits(LED2_GPIO, LED2_PIN)
#define LED3_ON GPIO_ResetBits(LED3_GPIO, LED3_PIN)
#define LED4_ON GPIO_ResetBits(LED4_GPIO, LED4_PIN)

//on chassis leds
#define LED_MOTOR1_CW_ON GPIO_SetBits(LED_MOTOR1_CW_GPIO, LED_MOTOR1_CW_PIN)
#define LED_MOTOR1_CCW_ON GPIO_SetBits(LED_MOTOR1_CCW_GPIO, LED_MOTOR1_CCW_PIN)
#define LED_MOTOR2_CW_ON GPIO_SetBits(LED_MOTOR2_CW_GPIO, LED_MOTOR2_CW_PIN)
#define LED_MOTOR2_CCW_ON GPIO_SetBits(LED_MOTOR2_CCW_GPIO, LED_MOTOR2_CCW_PIN)
#define LED_MOTOR3_CW_ON GPIO_SetBits(LED_MOTOR3_CW_GPIO, LED_MOTOR3_CW_PIN)
#define LED_MOTOR3_CCW_ON GPIO_SetBits(LED_MOTOR3_CCW_GPIO, LED_MOTOR3_CCW_PIN)

#define LED_MOTOR1_CW_OFF GPIO_ResetBits(LED_MOTOR1_CW_GPIO, LED_MOTOR1_CW_PIN)
#define LED_MOTOR1_CCW_OFF GPIO_ResetBits(LED_MOTOR1_CCW_GPIO, LED_MOTOR1_CCW_PIN)
#define LED_MOTOR2_CW_OFF GPIO_ResetBits(LED_MOTOR2_CW_GPIO, LED_MOTOR2_CW_PIN)
#define LED_MOTOR2_CCW_OFF GPIO_ResetBits(LED_MOTOR2_CCW_GPIO, LED_MOTOR2_CCW_PIN)
#define LED_MOTOR3_CW_OFF GPIO_ResetBits(LED_MOTOR3_CW_GPIO, LED_MOTOR3_CW_PIN)
#define LED_MOTOR3_CCW_OFF GPIO_ResetBits(LED_MOTOR3_CCW_GPIO, LED_MOTOR3_CCW_PIN)

//leds adc
#define LED_ADC_RED_ON GPIO_SetBits(LED_ADC_RED_GPIO, LED_ADC_RED_PIN)
#define LED_ADC_GREEN_ON GPIO_SetBits(LED_ADC_GREEN_GPIO, LED_ADC_GREEN_PIN)

#define LED_ADC_RED_OFF GPIO_ResetBits(LED_ADC_RED_GPIO, LED_ADC_RED_PIN)
#define LED_ADC_GREEN_OFF GPIO_ResetBits(LED_ADC_GREEN_GPIO, LED_ADC_GREEN_PIN)

void initializeLEDGPIO();
void LED_off();
void LEDs_SHOW_OFF();

#endif
